
name: 'sample workflow'

on:
    workflow_dispatch: 
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name : "Bijoy"
          run: echo "Hello"
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name : "Andrea"
          run : |
            echo "The deployment is successfull"
            echo "Success...!!"
